### ISSUE TITLE
Break python-indent-offset

### ISSUE THREAD

**Issue by Pitometsu** [thierryvolpiatto/helm-ipython#1]
Not sure how, but after just installing `helm-ipython`, my `python-indent-offset` changes from 4 to 2.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> Not sure how, but after just installing helm-ipython, my
> python-indent-offset changes from 4 to 2.

I am not using this, nor maintaining it anymore, so no idea what's
wrong.

Sorry, thanks.

--
Thierry

**Comment by Pitometsu** [comment]
Ok, thank you for feedback anyway.
